### ISSUE TITLE
Can we get the sourcecode of the launcher? / How to change the server ip?

### ISSUE THREAD

**Issue by MondoGao** [marcosppastor/launcher-maplestory-v142#1]
I want to share the server to my friend, but I can't change the ip that the redirector points to by hex edit.

**Comment by marcosppastor** [comment]
> I want to share the server to my friend, but I can't change the ip that the redirector points to by hex edit.

I only provided the "localhost", so is only possible to access it on your local machine.
Please view my GitHub in this Saturday (22), because i will publish the project source (so you can change the IP and build to the IP of you prefer).

**Comment by MondoGao** [comment]
Thank you very much!
